- hosts: 127.0.0.1

  vars:
    jenkins_version: "2.215-alpine"
    jenkins_url: http://127.0.0.1
    jenkins_port: 8080
    jenkins_install_via: "docker"
    jenkins_jobs: [
        "my-first-job",
      ]
    jenkins_auth: "none"
  roles:
    - emmetog.jenkins
